//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.History.Resources.MainMenu {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainMenuResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainMenuResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Service.History.Resources.MainMenu.MainMenuResources", typeof(MainMenuResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Details.
        /// </summary>
        public static string SubTitleAccountDetails {
            get {
                return ResourceManager.GetString("SubTitleAccountDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Your Password.
        /// </summary>
        public static string SubTitleChangeYourPassword {
            get {
                return ResourceManager.GetString("SubTitleChangeYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create External Login.
        /// </summary>
        public static string SubTitleCreateExternalLogin {
            get {
                return ResourceManager.GetString("SubTitleCreateExternalLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string SubTitleHistory {
            get {
                return ResourceManager.GetString("SubTitleHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string SubTitleTasks {
            get {
                return ResourceManager.GetString("SubTitleTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle List.
        /// </summary>
        public static string SubTitleVehicleList {
            get {
                return ResourceManager.GetString("SubTitleVehicleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Setup.
        /// </summary>
        public static string SubTitleVehicleSetup {
            get {
                return ResourceManager.GetString("SubTitleVehicleSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Type Setup.
        /// </summary>
        public static string SubTitleVehicleTypeSetup {
            get {
                return ResourceManager.GetString("SubTitleVehicleTypeSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string TitleAdministration {
            get {
                return ResourceManager.GetString("TitleAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgotten password.
        /// </summary>
        public static string TitleForgottenPassword {
            get {
                return ResourceManager.GetString("TitleForgottenPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string TitleHome {
            get {
                return ResourceManager.GetString("TitleHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string TitleLogIn {
            get {
                return ResourceManager.GetString("TitleLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string TitleLogOut {
            get {
                return ResourceManager.GetString("TitleLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Profile.
        /// </summary>
        public static string TitleManageProfile {
            get {
                return ResourceManager.GetString("TitleManageProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MainMenu.
        /// </summary>
        public static string TitleMenuName {
            get {
                return ResourceManager.GetString("TitleMenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register new account.
        /// </summary>
        public static string TitleRegisterNewAccount {
            get {
                return ResourceManager.GetString("TitleRegisterNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string TitleServices {
            get {
                return ResourceManager.GetString("TitleServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicles.
        /// </summary>
        public static string TitleVehicles {
            get {
                return ResourceManager.GetString("TitleVehicles", resourceCulture);
            }
        }
    }
}
